// playground/zod4-mock/hifi/leftrail.jsx
// hifi/leftrail.jsx
function LeftRail({ activeSubject = "User" }) {
  const { Icon, SUBJECTS, RELATIONSHIPS } = window;
  return (
    <aside className="rail">
      <section className="accordion-section" data-open="false">
        <div className="accordion-head">
          <span className="chev">▶</span>
          <span className="accordion-title">World</span>
          <span className="accordion-meta">seed 42</span>
        </div>
      </section>

      <section
        className="accordion-section"
        data-open="true"
        style={{ flex: 1, display: "flex", flexDirection: "column", minHeight: 0 }}
      >
        <div className="accordion-head">
          <span className="chev">▶</span>
          <span className="accordion-title">Subjects</span>
          <span className="accordion-meta">{SUBJECTS.length}</span>
        </div>
        <div className="accordion-body" style={{ flex: 1, overflow: "auto" }}>
          <div className="subj-list">
            {SUBJECTS.map((s) => (
              <div key={s.id} className="subj" aria-selected={activeSubject === s.id}>
                <span className="grip">⋮⋮</span>
                <span className="name">{s.id}</span>
                <span className="count">{s.count}</span>
                {s.badges.map((b, i) => (
                  <span key={i} className="badge">
                    {b}
                  </span>
                ))}
              </div>
            ))}
            <div className="add-row">
              <Icon name="plus" size={11} /> add subject
            </div>
          </div>

          <div className="sub-h">
            Relationships <span className="h-count">· {RELATIONSHIPS.length}</span>
            <span className="h-add">
              <Icon name="plus" size={11} />
            </span>
          </div>
          {RELATIONSHIPS.map((r, i) => (
            <div key={i} className="rel">
              <span className="from">{r.from}</span>
              <span className="arr">─</span>
              <span className="card">{r.card}</span>
              <span className="arr">─</span>
              <span className="to">{r.to}</span>
            </div>
          ))}
        </div>
      </section>

      <section className="accordion-section" data-open="false">
        <div className="accordion-head">
          <span className="chev">▶</span>
          <span className="accordion-title">Schemas</span>
          <span className="accordion-meta">2</span>
        </div>
      </section>
    </aside>
  );
}
window.LeftRail = LeftRail;

// playground/src/lib/components/Surfaces/LeftRail.svelte
<script lang="ts">
	import Accordion from '../Primitives/Accordion.svelte';
	import SubjectItem from '../Builder/SubjectItem.svelte';

	interface Subject {
		name: string;
		count?: number;
		badge?: string;
		selected?: boolean;
	}

	interface Section {
		title: string;
		meta?: string;
		open: boolean;
		id: string;
	}

	interface Props {
		sections?: Section[];
		subjects?: Subject[];
		onselectsubject?: (name: string) => void;
		onaddsubject?: () => void;
		ontogglesection?: (id: string) => void;
	}

	let {
		sections = [
			{ title: 'World', meta: 'seed 42', open: false, id: 'world' },
			{ title: 'Subjects', meta: '3', open: true, id: 'subjects' },
			{ title: 'Schemas', meta: '2', open: false, id: 'schemas' }
		],
		subjects = [
			{ name: 'User', count: 6, selected: true },
			{ name: 'Order', count: 4, badge: 'FK→User' },
			{ name: 'Product', count: 5 }
		],
		onselectsubject,
		onaddsubject,
		ontogglesection
	}: Props = $props();
</script>

<aside class="rail">
	{#each sections as section}
		<Accordion
			title={section.title}
			meta={section.meta}
			open={section.open}
			ontoggle={() => ontogglesection?.(section.id)}
		>
			{#if section.id === 'subjects'}
				<div class="subj-list">
					{#each subjects as subj}
						<SubjectItem
							name={subj.name}
							count={subj.count}
							badge={subj.badge}
							selected={subj.selected}
							onclick={() => onselectsubject?.(subj.name)}
						/>
					{/each}
					<!-- svelte-ignore a11y_click_events_have_key_events -->
					<!-- svelte-ignore a11y_no_static_element_interactions -->
					<div class="add-row t-code-sm" onclick={onaddsubject}>
						<span class="plus">+</span> add subject
					</div>
				</div>
			{/if}
		</Accordion>
	{/each}
</aside>

<style>
	.rail {
		width: 264px;
		height: 100%;
		background: var(--bg-1);
		border-right: 1px solid var(--line);
		display: flex;
		flex-direction: column;
		user-select: none;
	}

	.subj-list {
		display: flex;
		flex-direction: column;
		gap: 1px;
	}

	.add-row {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: var(--space-2);
		padding: var(--space-1) var(--space-3);
		margin-top: 2px;
		border: 1px dashed var(--line-strong);
		border-radius: var(--r-sm);
		color: var(--ink-2);
		cursor: pointer;
	}
	.add-row:hover {
		color: var(--ink-0);
		border-color: var(--accent-edge);
		background: var(--accent-soft);
	}
	.add-row .plus {
		font-size: 14px;
		line-height: 1;
		margin-bottom: 2px;
	}
</style>
