// playground/zod4-mock/hifi/row.jsx
// hifi/row.jsx — single property row + group header.
function Row({
  keyName,
  type,
  mods = [],
  indent = 0,
  selected,
  warn,
  addMenuOpen,
  addMenuRef,
  onAddMod,
}) {
  const { Mod, AddMod, TypeChip, Icon } = window;
  return (
    <div
      className="row"
      data-selected={selected || undefined}
      data-warn={warn || undefined}
      style={{ "--ind": 12 + indent * 18 + "px" }}
    >
      <span className="grip">⋮⋮</span>
      <input className="key mono" defaultValue={keyName} size={Math.max(keyName.length, 4)} />
      <span className="colon">:</span>
      <TypeChip value={type} active={selected} />
      {mods.map(([name, value, warnFlag], i) => (
        <Mod
          key={i}
          name={name}
          value={value}
          warn={warnFlag === "warn"}
          removable={selected && i === 0}
        />
      ))}
      <AddMod ref={addMenuOpen ? addMenuRef : null} active={addMenuOpen} onClick={onAddMod} />
      <span className="spacer" />
      {warn && (
        <span className="row-warn">
          <Icon name="warn" size={13} />
        </span>
      )}
    </div>
  );
}

function GroupHead({ name, type, indent = 0 }) {
  const { TypeChip } = window;
  return (
    <div className="group-head" style={{ paddingLeft: 12 + indent * 18 }}>
      <span className="chev">▾</span>
      <span className="gname">{name}</span>
      <span className="colon">:</span>
      <TypeChip value={type} />
    </div>
  );
}

function CardinalityRow({ indent = 1, mods = [] }) {
  const { Mod, AddMod } = window;
  return (
    <div
      className="row"
      style={{
        paddingLeft: 12 + indent * 18,
        color: "var(--ink-2)",
        fontFamily: "JetBrains Mono, monospace",
        fontSize: 11,
      }}
    >
      <span>cardinality:</span>
      {mods.map(([name, value], i) => (
        <Mod key={i} name={name} value={value} />
      ))}
      <AddMod />
    </div>
  );
}

window.Row = Row;
window.GroupHead = GroupHead;
window.CardinalityRow = CardinalityRow;

// playground/src/lib/components/Builder/Row.svelte
<script lang="ts">
	import TypeChip from '../Primitives/TypeChip.svelte';
	import ModPill from './ModPill.svelte';
	import AddModPill from './AddModPill.svelte';

	interface Modifier {
		name: string;
		value?: string | number;
		warn?: boolean;
	}

	interface Props {
		keyName: string;
		type: string;
		mods?: Modifier[];
		selected?: boolean;
		warn?: boolean;
		indent?: number;
		onselect?: () => void;
		onchangekey?: (name: string) => void;
		onchangetype?: () => void;
		onaddmod?: () => void;
	}

	let {
		keyName = $bindable(),
		type,
		mods = [],
		selected = false,
		warn = false,
		indent = 0,
		onselect,
		onchangekey,
		onchangetype,
		onaddmod
	}: Props = $props();
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
	class="row"
	data-selected={selected}
	data-warn={warn}
	style="--ind: {12 + indent * 20}px"
	onclick={onselect}
>
	<span class="grip">⋮⋮</span>
	<input
		class="key mono"
		bind:value={keyName}
		size={keyName?.length || 1}
	/>
	<span class="colon">:</span>
	<TypeChip {type} active={selected} onclick={onchangetype} />

	{#each mods as mod}
		<ModPill name={mod.name} value={mod.value} warn={mod.warn} removable={true} />
	{/each}

	<AddModPill onclick={onaddmod} />
</div>

<style>
	.row {
		display: flex;
		align-items: center;
		gap: 6px;
		min-height: var(--row-h);
		padding: 4px 12px 4px var(--ind, 12px);
		border-bottom: 1px solid var(--bg-2);
		position: relative;
		flex-wrap: wrap;
		transition: background var(--ease-quick);
	}
	.row:hover {
		background: var(--bg-2);
	}
	.row[data-selected='true'] {
		background: var(--accent-soft);
		box-shadow: inset 2px 0 0 var(--accent);
	}
	.row[data-warn='true'] {
		background: var(--warn-soft);
		box-shadow: inset 2px 0 0 var(--warn);
	}

	.row .grip {
		color: var(--ink-3);
		font-family: 'JetBrains Mono', monospace;
		font-size: 11px;
		cursor: grab;
		opacity: 0;
		transition: opacity var(--ease-quick);
	}
	.row:hover .grip {
		opacity: 1;
	}

	.row .key {
		background: transparent;
		border: 0;
		color: var(--ink-0);
		font-family: 'JetBrains Mono', monospace;
		font-size: 12px;
		padding: 2px 0;
		min-width: 0;
		width: auto;
	}
	.row .key:focus {
		outline: 0;
		color: var(--accent-bright);
	}
	.row .colon {
		color: var(--ink-3);
		font-family: 'JetBrains Mono', monospace;
	}
</style>
